/* eslint no-unused-expressions: 0 */

import { FileSystemWriter } from '../../../src/file-handling/file-system-writer';
import { ERRORS } from '../../../src/errors';
import requestFileSystemMock, { FILE_URL, WRITE_STATUS } from '../../helpers/request-file-system-mock';
const FILE_NAME = 'testFileName';
const FILE_SIZE = 1024;

describe('FileSystemWriter', () => {
    describe('constructor()', () => {
        it('should expose fileName and fileSize', () => {
            const writer = new FileSystemWriter(FILE_NAME, FILE_SIZE);

            expect(writer.fileName).to.equal(FILE_NAME);
            expect(writer.fileSize).to.equal(FILE_SIZE);
        });
    });

    describe('isSupported()', () => {
        it('should return true when File System API works', async () => {
            window.requestFileSystem = (storageType, size, onSuccess, onError) => {
                expect(storageType).to.equal(window.TEMPORARY);
                expect(size).to.equal(1);
                expect(typeof onSuccess).to.equal('function');
                expect(typeof onError).to.equal('function');

                onSuccess();
            };

            const result = await FileSystemWriter.isSupported();
            expect(result).to.be.true;
        });

        it('should return false when File System API doesn\'t work', async () => {
            window.requestFileSystem = (storageType, size, onSuccess, onError) => {
                expect(storageType).to.equal(window.TEMPORARY);
                expect(size).to.equal(1);
                expect(typeof onSuccess).to.equal('function');
                expect(typeof onError).to.equal('function');

                onError();
            };

            const result = await FileSystemWriter.isSupported();
            expect(result).to.be.false;
        });

        it('should return false when File System API is not supported', async () => {
            window.requestFileSystem = null;
            window.webkitRequestFileSystem = null;

            const result = await FileSystemWriter.isSupported();
            expect(result).to.be.false;
        });
    });

    describe('init()', () => {
        it('should initialize writer and prepare file to write', async () => {
            FileSystemWriter.isSupported = () => true;
            requestFileSystemMock();

            const writer = new FileSystemWriter(FILE_NAME, FILE_SIZE);
            await writer.init();

            expect(writer.fileEntry).to.not.be.undefined;
            expect(writer.fileWriter).to.not.be.undefined;
        });

        it('shouldn\'t initialize writer when File System API is not supported', async () => {
            FileSystemWriter.isSupported = () => false;

            const writer = new FileSystemWriter(FILE_NAME, FILE_SIZE);

            try {
                await writer.init();
            } catch (error) {
                expect(error).to.deep.equal({ error: ERRORS.FILE_SYSTEM_API_NOT_SUPPORTED });
            }
        });
    });

    describe('requestFileSystem()', () => {
        it('should return global requestFileSystem method or webkitRequestFileSystem method', () => {
            window.requestFileSystem = 'requestFileSystem';
            window.webkitRequestFileSystem = 'webkitRequestFileSystem';
            expect(FileSystemWriter.requestFileSystem()).to.equal('requestFileSystem');
            window.requestFileSystem = null;
            expect(FileSystemWriter.requestFileSystem()).to.equal('webkitRequestFileSystem');
            window.webkitRequestFileSystem = null;
            expect(FileSystemWriter.requestFileSystem()).to.be.null;
        });
    });

    describe('write()', () => {
        it('should call write method on fileWriter object and wait for onwriteend event', async () => {
            FileSystemWriter.isSupported = () => true;
            requestFileSystemMock();

            const writer = new FileSystemWriter(FILE_NAME, FILE_SIZE);
            await writer.init();
            await writer.write();
            expect(writer.fileWriter.status).to.equal(WRITE_STATUS.FINISHED);
        });
    });

    describe('getFileURL()', () => {
        it('should return URL to file generated by fileWriter', async () => {
            FileSystemWriter.isSupported = () => true;
            requestFileSystemMock();

            const writer = new FileSystemWriter(FILE_NAME, FILE_SIZE);
            await writer.init();

            expect(writer.getFileURL()).to.equal(FILE_URL);
        });
    });
});
