export const IPFS_HOST = '127.0.0.1';
export const IPFS_PORT = '5002';
export const IPFS_PROTOCOL = 'http';
export const FILE_NAME = 'test.txt';
export const IPFS_HASH_LENGTH = 46;
export const FILE_CONTENT = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pulvinar mollis dolor. Etiam porta ornare vestibulum. Nam vitae odio mauris. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec id ex sed nisl maximus accumsan ut id odio. Maecenas non vehicula augue. Cras luctus sem malesuada ex congue semper. Quisque vel sodales ipsum, sit amet vulputate sem. Vivamus tempus venenatis libero, non molestie libero varius eu. Pellentesque ornare suscipit nulla, a tristique erat laoreet et. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam sed fermentum odio. Nam non mauris dictum, commodo odio maximus, dignissim augue. Curabitur porttitor nunc ligula. Nulla facilisi.
Sed cursus nulla magna. Integer imperdiet eleifend diam, et tincidunt mauris facilisis non. In quis luctus libero, ac aliquet justo. Praesent pharetra vel ipsum quis laoreet. Morbi luctus ante ac dictum imperdiet. Maecenas egestas lobortis odio. Nam tincidunt lacus in ante congue tincidunt. Donec lobortis odio nec rhoncus egestas. Mauris a rhoncus metus, a vulputate diam. Nullam sodales nisl sit amet magna dapibus mollis. Mauris tempor magna accumsan ex facilisis, a dapibus nisi tincidunt. Vestibulum vitae lobortis erat, id elementum lorem. Vivamus laoreet imperdiet nunc et feugiat. Sed vulputate leo in massa tempor auctor. Donec ut nisi malesuada, sollicitudin lacus sed, finibus erat. Donec porttitor ultrices turpis ac aliquam.
Fusce eget iaculis mauris. Aliquam erat volutpat. In vitae urna ac nibh ultrices luctus ac in justo. Suspendisse congue mattis dui quis ultricies. Donec blandit nibh in quam sodales, at luctus sem sodales. Duis cursus est sed volutpat ornare. Aenean ultricies magna nunc, at ornare nisi tincidunt nec. Quisque condimentum nisi sed urna euismod sagittis. Donec imperdiet nulla sit amet enim vehicula posuere. Morbi dignissim turpis et faucibus euismod. In hac habitasse platea dictumst. Sed blandit odio augue, placerat fringilla nunc vehicula sit amet.
Duis venenatis metus quis elit maximus, eget facilisis ipsum mattis. Suspendisse fermentum lorem sed finibus efficitur. Curabitur non neque neque. Etiam mauris nunc, tristique ut sollicitudin et, ultrices et nulla. Donec vulputate ullamcorper sem at elementum. Phasellus dignissim lacinia neque, ac commodo est blandit a. Quisque at magna semper, gravida quam quis, condimentum velit. Mauris iaculis porta ligula. Ut ut justo sodales, dictum purus ut, iaculis mi. Vivamus aliquet finibus tincidunt. Integer arcu nunc, condimentum non erat non, luctus hendrerit elit. Sed magna magna, pretium viverra felis at, porta vehicula velit. Donec efficitur velit efficitur sagittis dignissim. Etiam in tellus porttitor, vestibulum mi in, lobortis velit. Praesent vulputate, lorem at accumsan scelerisque, sem tortor faucibus metus, consectetur consequat est mauris sed diam.
Donec sit amet nibh dui. Praesent vulputate lectus felis. Nam varius nibh viverra, tempus lorem vel, mattis tortor. Integer dignissim faucibus blandit. Quisque vitae nisi vehicula magna tincidunt aliquam. Vestibulum eget ligula eu lacus elementum interdum in ac dui. Nulla nec rhoncus quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris feugiat neque a urna finibus rutrum. Sed congue consectetur quam eu condimentum. Donec a mauris euismod, condimentum dolor porta, dapibus metus. Vivamus tincidunt, lacus ac euismod lobortis, augue velit semper metus, non aliquet neque mi a elit. Suspendisse vel blandit lacus. Donec pretium consectetur orci id lobortis.`;
